### PR TITLE
Adjusted ServerRole when using SingleServerFarm

### PR DESCRIPTION
**Pull request by farapholch**
Wrong serveRole specified, it should be 'SingleServer' not 'SingleServerFarm'.

### CODE REVIEW

**Comment by brianlala** [comment]
Hmm I haven't tested this yet, but according to this documentation it should still be "SingleServerFarm": https://docs.microsoft.com/en-us/sharepoint/administration/role-conversion-using-minrole-in-sharepoint-server-2016#how-to-change-a-server-role

**Comment by farapholch** [comment]
> Hmm I haven't tested this yet, but according to this documentation it should still be "SingleServerFarm": https://docs.microsoft.com/en-us/sharepoint/administration/role-conversion-using-minrole-in-sharepoint-server-2016#how-to-change-a-server-role

Thanks for reply :)

I was unable to launch psconfig when the value SingleServerFarm was set for the registry key "Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Shared Tools\Web Server Extensions\16.0\WSS\ServerRole" but when I set this to "SingleServer" the wizard starts and I can proceed with the configuration.

See image below:

image

**Comment by brianlala** [comment]
What version of SharePoint is this happening on? Are you trying to run PSConfig manually, or in the context of AutoSPInstaller?

**Comment by farapholch** [comment]
> What version of SharePoint is this happening on? Are you trying to run PSConfig manually, or in the context of AutoSPInstaller?

Hi, we are running SPSE and this fails both if I run it in the AutoSP Context (null reference value) or manually when starting psconfigUI.

**Comment by brianlala** [comment]
OK I'll try to repro now, stay tuned.

**Comment by brianlala** [comment]
If you do a `Set-SPServer -Role` and then tab through the options you should see BOTH SingleServer and SingleServerFarm. I'm assuming they're both valid and equivalent. 

I just built a farm using SingleServerFarm and it worked fine.
image

And when I checked the registry, my server role actually was listed as APPLICATION even though central admin and PowerShell both report Single-Server Farm.

I'm running Subscription Edition with the January PU.

**Comment by farapholch** [comment]
> If you do a `Set-SPServer -Role` and then tab through the options you should see BOTH SingleServer and SingleServerFarm. I'm assuming they're both valid and equivalent.
> 
> I just built a farm using SingleServerFarm and it worked fine. image
> 
> And when I checked the registry, my server role actually was listed as APPLICATION even though central admin and PowerShell both report Single-Server Farm.
> 
> I'm running Subscription Edition with the January PU.

Thanks for looking into this. The Registry made me confused about this (Application) and I thought the value would be the same as the actual min role.  

Not sure why we got the error in the first place but we can close this by now.

**Pull request closed without merging**
